plugins {
    id 'java-library'
}

dependencies {
    //General Modules Dependencies
    api project(':erp-common')
    api project(':erp-domain')
    api project(':erp-application')

    //PostgreSQL
    api("org.postgresql:postgresql")
    api("org.springframework.boot:spring-boot-starter-data-jpa")

    //Mongo
    api("org.springframework.boot:spring-boot-starter-data-mongodb")

    //Redis
    api("org.springframework.boot:spring-boot-starter-data-redis")
    api("org.springframework.boot:spring-boot-starter-cache")

}